import { AlertTriangle, Check, ChevronRight, CircleAlert, ShieldCheck } from "lucide-react";

export function ProvenanceBadge({ label }) { return <span className="provenance">{label}</span>; }
export function StatusBadge({ status = "pass" }) { const fail = ["fail", "blocked", "degraded"].includes(status); return <span className={`status ${fail ? "status-warn" : "status-ok"}`}>{fail ? <CircleAlert size={12} /> : <Check size={12} />}{status}</span>; }
export function MetricCard({ label, value, detail, provenance = [] }) { return <section className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small><div>{provenance.map((item) => <ProvenanceBadge key={item} label={item} />)}</div></section>; }
export function LifecycleStepper({ stages, active = "Investigate" }) { return <div className="lifecycle">{stages.map((stage, index) => <div className={`life-stage ${stage === active ? "active" : ""}`} key={stage}><span>{index + 1}</span>{stage}</div>)}</div>; }
export function ServiceStatusCard({ service }) { return <article className="service-card"><div><strong>{service.name}</strong><small>{service.readiness} · {service.dependencies} dependencies</small></div><StatusBadge status={service.health} /></article>; }
export function EvidencePanel({ title = "Evidence bundle", items = [] }) { return <section className="panel"><h3>{title}</h3><div className="evidence-list">{items.map((item) => <div key={item}><Check size={14} />{item}</div>)}</div></section>; }
export function GuardChecklist({ checks }) { return <section className="panel"><h3>SentinelGuard checks</h3>{checks.map((check) => <div className="check-row" key={check.label}><span>{check.label}</span><StatusBadge status={check.status} /></div>)}</section>; }
export function ExecutionTimeline() { return <section className="panel"><h3>Controlled execution timeline</h3><ol className="timeline"><li>Execution request · local target</li><li>Human approval · approved</li><li>Final gate · passed</li><li>Sandbox adapter · rollback only</li><li>Post-live and post-ready · verified</li></ol></section>; }
export function AgentCard({ name }) { const description = { Investigator: "Reviews evidence and leading candidate.", Challenger: "Attempts to disprove the hypothesis.", Remediation: "Reviews plan and Guard state.", Verifier: "Reviews recovery evidence." }[name]; return <article className="agent-card"><ShieldCheck size={18} /><strong>{name}</strong><p>{description}</p><small>Execution authority: disabled</small><small>RCA confirmation: disabled</small></article>; }
export function EmptyState({ title, detail }) { return <section className="empty"><AlertTriangle size={20} /><strong>{title}</strong><p>{detail}</p></section>; }
export function DetailLink() { return <ChevronRight size={16} aria-hidden="true" />; }
