import { AlertTriangle, CircleDashed, Database, LockKeyhole, ShieldAlert } from "lucide-react";
import { AgentCard, EvidencePanel, ExecutionTimeline, GuardChecklist, LifecycleStepper, MetricCard, ProvenanceBadge, ServiceStatusCard, StatusBadge } from "../components/ui.jsx";
const rcaEvidence = ["Anomaly signal on payment-service", "Recent local change event", "Directed graph relationship", "Incident correlation evidence"];

function Section({ children }) { return <div className="content">{children}</div>; }
function Table({ rows, headers }) { return <div className="table"><div className="tr th">{headers.map((h) => <span key={h}>{h}</span>)}</div>{rows}</div>; }

export function ControlView({ path, scenario }) {
  const incident = scenario.incident;
  if (path === "/") return <Section><div className="hero"><div><span className="eyebrow">ACTIVE DETERMINISTIC SCENARIO</span><h2>{incident.id} · {incident.service} degradation</h2><p>Evidence-grounded investigation with a verified local sandbox rollback outcome.</p><div>{scenario.provenance.map((p) => <ProvenanceBadge key={p} label={p} />)}</div></div><StatusBadge status="recovery verified" /></div><LifecycleStepper stages={scenario.lifecycle} /><div className="metrics"><MetricCard label="Active incident" value={incident.id} detail="Correlated evidence bundle" provenance={["SYNTHETIC"]} /><MetricCard label="Failure warning" value="0.72" detail="Development early-warning risk" provenance={["DEVELOPMENT DATA", "NOT MEASURED"]} /><MetricCard label="Leading RCA" value="payment-service" detail="Supported candidate hypothesis" provenance={["SYNTHETIC"]} /><MetricCard label="Guard state" value="eligible_pending_human" detail="Not execution authorization" provenance={["LOCAL"]} /></div><div className="grid two"><EvidencePanel title="Current decision boundary" items={["Planner recommendation is not Guard approval", "Guard approval is not human authorization", "Human authorization is not execution"]} /><ExecutionTimeline /></div></Section>;
  if (path === "/services") return <Section><div className="metrics"><MetricCard label="Demo services" value="7" detail="Local service topology" provenance={["LOCAL"]} /><MetricCard label="Degraded" value="1" detail="payment-service scenario" provenance={["SYNTHETIC"]} /></div><div className="service-grid">{scenario.services.map((service) => <ServiceStatusCard key={service.name} service={service} />)}</div><EvidencePanel title="Dependency topology" items={["api-gateway → user-service, order-service, auth-service", "order-service → payment-service, inventory-service, notification-service"]} /></Section>;
  if (path === "/telemetry") return <Section><div className="metrics">{Object.entries(scenario.telemetry).filter(([k]) => k !== "provenance").map(([label, value]) => <MetricCard key={label} label={label.replace(/([A-Z])/g, " $1")} value={value} detail="Deterministic demo signal" provenance={scenario.telemetry.provenance} />)}</div><EvidencePanel title="Supported telemetry categories" items={["Metrics", "Structured telemetry and log signals", "Traces", "Change events", "Health signals"]} /></Section>;
  if (path === "/prediction") return <Section><div className="metrics">{[["Precision", scenario.prediction.precision], ["Recall", scenario.prediction.recall], ["F1", scenario.prediction.f1], ["Average lead", scenario.prediction.lead], ["Warning risk", scenario.prediction.risk]].map(([label, value]) => <MetricCard key={label} label={label} value={value} detail="Development evaluation / demo warning" provenance={scenario.prediction.provenance} />)}</div><div className="callout"><AlertTriangle />Not production-calibrated. These are development/synthetic measurements.</div></Section>;
  if (path === "/incidents") return <Section><div className="panel incident"><span className="eyebrow">EVIDENCE BUNDLE</span><h2>{incident.id} · {incident.severity} · {incident.priority}</h2><p>Affected service: {incident.service}. Incident correlation does not confirm root cause.</p><div>{rcaEvidence.map((e) => <ProvenanceBadge key={e} label={e} />)}</div></div><EvidencePanel title="Correlation evidence" items={["Temporal proximity", "Dependency graph relationship", "Anomaly strength", "Service membership"]} /></Section>;
  if (path === "/rca") return <Section><div className="grid two"><section className="panel candidate"><span className="eyebrow">LEADING RCA CANDIDATE</span><h2>payment-service</h2><StatusBadge status="supported candidate hypothesis" /><p>Candidate remains unconfirmed. No agent independently confirms root cause.</p></section><EvidencePanel title="Candidate evidence" items={rcaEvidence} /></div></Section>;
  if (path === "/challenger") return <Section><section className="panel"><span className="eyebrow">ADVERSARIAL CHALLENGE</span><h2>Attempt to disprove payment-service hypothesis</h2><div className="check-row"><span>Contradictory evidence</span><StatusBadge status="none found in demo" /></div><div className="check-row"><span>Alternative candidates</span><StatusBadge status="inconclusive" /></div><div className="check-row"><span>Challenge result</span><StatusBadge status="supported candidate hypothesis" /></div><p>Supported is not confirmed root cause.</p></section></Section>;
  if (path === "/counterfactuals") return <Section><Table headers={["Action", "Baseline", "Projected", "Reduction", "Net benefit", "Execution boundary"]} rows={scenario.counterfactuals.map((row) => <div className="tr" key={row.action}><strong>{row.action}</strong><span>{row.baseline}</span><span>{row.projected}</span><span>{row.reduction}</span><span>{row.netBenefit}</span><span>{row.boundary}</span></div>)} /><div className="callout"><CircleDashed />SIMULATED decision support. Only rollback has a configured sandbox adapter.</div></Section>;
  if (path === "/priority") return <Section><div className="metrics"><MetricCard label="Service criticality" value="high" detail="Payment workflow dependency" provenance={["SYNTHETIC"]} /><MetricCard label="Latency SLO signal" value="burning" detail="Decision support input" provenance={["SYNTHETIC"]} /><MetricCard label="Blast radius" value="1 upstream" detail="Graph-derived demo context" provenance={["SYNTHETIC"]} /><MetricCard label="Priority" value="P1" detail="Local decision-support value" provenance={["LOCAL", "SYNTHETIC"]} /></div></Section>;
  if (path === "/remediation") return <Section><div className="grid two"><section className="panel"><span className="eyebrow">PLANNER RECOMMENDATION</span><h2>rollback payment-service</h2><p>Counterfactual benefit: 0.40 · Rollback available: yes</p><StatusBadge status="proposed_pending_guard" /></section><EvidencePanel title="State hierarchy" items={["Planner Recommendation ≠ SentinelGuard Approval", "SentinelGuard Approval ≠ Human Authorization", "Human Authorization ≠ Execution"]} /></div></Section>;
  if (path === "/guard") return <Section><div className="guard-head"><ShieldAlert /><div><h2>eligible_pending_human</h2><p>Technical eligibility is not execution authorization.</p></div></div><GuardChecklist checks={scenario.guardChecks} /></Section>;
  if (path === "/recovery") return <Section><div className="callout"><LockKeyhole />LOCAL SANDBOX · rollback is the only configured sandbox execution adapter.</div><ExecutionTimeline /><div className="grid two"><EvidencePanel title="Final execution gate" items={["Human approval approved", "Local target validation passed", "Rollback validation passed", "Adapter validation: rollback"]} /><EvidencePanel title="Recovery result" items={["Post-live check passed", "Post-ready check passed", "Recovery verified", "traffic_shift and restart: adapter unavailable"]} /></div></Section>;
  if (path === "/investigation") return <Section><section className="panel"><span className="eyebrow">PHASE 15 GROUNDED INVESTIGATION</span><h2>Provider: {scenario.provider}</h2><p>Evidence sources: {incident.evidenceCount} · Retrieved runbooks: 2</p><div className="safety-list"><ProvenanceBadge label="AGENT RCA CONFIRMATION DISABLED" /><ProvenanceBadge label="AGENT EXECUTION DISABLED" /><ProvenanceBadge label="GUARD BYPASS DISABLED" /><ProvenanceBadge label="HUMAN-APPROVAL BYPASS DISABLED" /></div></section><div className="agent-grid">{scenario.agents.map((agent) => <AgentCard key={agent} name={agent} />)}</div></Section>;
  if (path === "/evidence") return <Section><EvidencePanel title="Traceable evidence and audit" items={["Incident INC-0001", "RCA hypothesis and challenger disposition", "Counterfactual simulation records", "Planner and SentinelGuard decision", "Human approval state", "Execution result and recovery verification"]} /><div className="callout"><Database />All identifiers and timestamps on this screen are deterministic demo data.</div></Section>;
  return <Section><div className="status-matrix">{[["Production infrastructure", "NOT CONNECTED"], ["Production telemetry", "NOT CONNECTED"], ["Production benchmark", "NOT MEASURED"], ["Controlled remediation", "LOCAL SANDBOX"], ["Counterfactual engine", "SIMULATED"], ["Phase 15 provider", "DETERMINISTIC"], ["Human authorization", "REQUIRED"]].map(([label, value]) => <div key={label}><span>{label}</span><ProvenanceBadge label={value} /></div>)}</div><EvidencePanel title="Phase completion map" items={["Phases 0–15: implemented repository evidence", "No Phase 16+ claim", "Production deployment: not established"]} /></Section>;
}
